apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../staging
  - local_service.yaml
patchesStrategicMerge:
  - patch_configmap_environment.yaml
  - patch_replica.yaml
images:
  - name: hello
    newName: explodio/hello
    newTag: latest
  - name: hello-flyway
    newName: explodio/hello/flyway
    newTag: latest
