FROM golang:1.15.5 AS build

RUN mkdir /src
WORKDIR /src

# Get dependencies, cached if we don't change mod/sum.
COPY go.mod .
COPY go.sum .
RUN go mod download

# Build with changed source files.
COPY . .
RUN go build -o /tokyo_server ./cmd/tokyo_server

FROM scratch AS bin
COPY --from=build /tokyo_server /
ENTRYPOINT ["/tokyo_server"]